### ISSUE TITLE
python35 available in repo

### ISSUE THREAD

**Issue by saft** [iuscommunity-pkg/python35u#2]
Hi, probably not the right place to ask this but I'm wondering why python 35 is not available from this repo: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/repoview/

I saw this: https://www.reddit.com/r/Python/comments/3ovsp2/ius_python_35_for_rhelcentos_67/ and expected to see it there.

**Comment by carlwgeorge** [comment]
Howdy @saft,

python35u is definitely available in the CentOS 7 stable repository.

```
$ rpm -qf /etc/redhat-release 
centos-release-7-2.1511.el7.centos.2.10.x86_64
$ yum info python35u
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.den.host-engine.com
 * epel: fedora-epel.mirror.lstn.net
 * extras: centos.den.host-engine.com
 * updates: centos.den.host-engine.com
Available Packages
Name        : python35u
Arch        : x86_64
Version     : 3.5.1
Release     : 1.ius.centos7
Size        : 49 k
Repo        : ius/x86_64
Summary     : Version 3 of the Python programming language aka Python 3000
URL         : http://www.python.org/
License     : Python
Description : Python 3 is a new version of the language that is incompatible with the 2.x
            : line of releases. The language is mostly the same, but many details, especially
            : how built-in objects like dictionaries and strings work, have changed
            : considerably, and a lot of deprecated features have finally been removed.
```

You don't see it on that exact webpage because it only shows the latest packages.  If you [jump to the letter p](https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/repoview/letter_p.group.html) (link in the top right), you will see it there.  It is also viewable if you go one directory up and [view the directory index](https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/), not the repoview webpage.

The best way to consume IUS package is to use our release RPM, as detailed in our [Getting Started Guide](https://ius.io/GettingStarted/).
